project:
  type: website
  output-dir: docs

metadata:
  project-root: "."

website:
  title: "Ordering App Project Docs"
  navbar:
    left:
      - text: Azure
        menu:
          - text: Overview
            href: architecture/azure/azure-overview.html
          - text: Ordering App
            href: architecture/azure/ordering-app/ordering-app.html
          - text: Product Manager App
            href: architecture/azure/product-manager/product-manager.html
          - text: HubSpot Service
            href: architecture/azure/hubspot-service/hubspot-service.html
          - text: PDF Service
            href: architecture/azure/pdf-service/pdf-service.html
          - text: SQL Database
            href: architecture/azure/terramax-data/terramax-data.html
          - text: App Images
            href: architecture/azure/terramaxappimages/terramaxappimages.html
      - href: architecture/github/github-overview.html
        text: Github
      - href: architecture/hubspot/hubspot-overview.html
        text: HubSpot
      - href: how-to/how-to-contents.html
        text: How-to's
      - href: reference/glossary.html
        text: Glossary

format:
  html: 
    embed-resources: true
    toc: true
    css: styles/glossary.css

filters: 
  - filters/tooltip.lua
