<!-- To regenerate the Markdown version of this file, enter in the terminal:
    quarto render docs/how-to/deploy-hubspot-service-update.qmd 
-->

---
title: "Deploy an Update to the hubspot-service app"
format: gfm
---

This guide walks through the process of deploying an update to the `hubspot-service` app where it is hosted in Azure Functions, so that it will become live and available to users.  

This is NOT a guide to writing Azure Functions, but to updating them the existing app.  It assumes that you are using VS Code and are logged in to the TerraMax Azure account.

The `hubspot-service` app is deployed in Azure Functions; more aobut this resource can be found in [Azure Functions](../azure/azure-functions.md)

---

## 1. Finalize and Build Update

- Once you are satisfied with your changes and are ready to deploy, you need to build to convert the Typescript files into Javascript.  In Vs Code, in the project folder, open a terminal and run `npm run build`.  This process may catch errors that need to be addressed before you can ry to build again.

## 2. Deploy with the VS Code Command Palette

- Find and select `Azure Functions: Deploy to Function app...` in the Command Palette.  There may be a lag in response after you click.
- Select the function app you are deploying from the dropdown list that appears: `terramax-hubspot-service`.
- A popup will ask if you are sure you want to deploy and overwrite the previous deployment.  Click `Deploy`.
- the Terminal will display the status of the deployment process, which may take some time.