<!-- To regenerate the Markdown version of this file, enter in the terminal:
    quarto render docs/how-to/deploy-ordering-app-update.qmd 
-->

---
title: "Deploy an Update to the ordering-app"
format: gfm
---

This guide walks through the process of deploying an update to the `ordering-app` where it is hosted in Azure Static Webapps, so that it will become live and available to users.  

This is NOT a guide to writing React or Typescript, but to deploying updates the existing app.  It assumes that you are using VS Code and are logged in to the [GitHub account](../github/github-account.qmd) that hosts the codebase.  It deploys via GitHub actions, and as of the writing of this document cannot be deployed any other way.

For this project, I have set up a `deploy` branch to be the one that triggers the necessary GitHub action.  Changes can be made, committed and synced to other branches including `main` without triggering an update.

---

## 1. Finalize and Build Update

- Once you are satisfied with your changes and are ready to deploy, you need to build to convert the Typescript files into Javascript.  In Vs Code, in the project folder, open a terminal and run `npm run build`.  This process may catch errors that need to be addressed before you can try to build again.

## 2. Commit and Sync to GitHub

- Commit all changes to the branch you're working on, and then sync those changes to GitHub.

## 3. Push Changes to the `deploy` Branch

- In a terminal enter `github push origin (branch):deploy`, replacing (branch) with the nameo fthe branch that has the changes you want to deploy.  Example:
    - `github push origin auth:deploy`

- This should be a quick process in Vs Code.  It will authomatically trigger the GitHub workflow to deploy the update, which will take longer.

## 4. Check Status in GitHub Actions

- In the [GitHub account](../github/github-account.qmd): 
    - open the `ordering-app` repo
    - go to the `Actions` tab
    - Select `All workflows` from the Actions sidebar (it may already be selected)

- In the `All workflows` section, you will see a list of past workflows, and the date they were attempted.  You may need to refresh to see the one you just triggered.  You may see a yellow circle to indicate that it's in progress; it will automatically change to show when it's complete.  

- If it turns red to indicate failure, click on the entry to view the error details.  Sometimes they are transient and you can try again; try rebuilding the app, re-committing, and redeploying.